Client: main.py
	@echo -e "\x1b[34m[\u001b[0m\x1b[31m*\x1b[34m\x1b[34m]\u001b[0m Build shell client binary..."
	@echo -e "\x1b[34m[\u001b[0m\x1b[31m#\x1b[34m\x1b[34m]\u001b[0m pyinstaller main.py"
	@pyinstaller -n nemo main.py