Server: main.go
	@echo -e "\x1b[34m[\u001b[0m\x1b[31m*\x1b[34m\x1b[34m]\u001b[0m Building teamserver binary..."
	@echo -e "\x1b[34m[\u001b[0m\x1b[31m#\x1b[34m\x1b[34m]\u001b[0m go build -o server -compiler gccgo payload.go"
	@# go build -x -v -o server -compiler gccgo payload.go
	@go build -o ../server ./main.go